import type { FinalReport, ReportSection, TrendChart, ComparisonTable, RiskItem, TimelineEvent, KeyQuote } from './types'

function sectionToMarkdown(section: ReportSection): string {
  let out = `## ${section.title}\n\n`

  switch (section.type) {
    case 'text':
      out += `${section.data as string}\n`
      break

    case 'trend_chart': {
      const c = section.data as TrendChart
      out += `| ${c.x_label} | ${c.y_label} (${c.unit}) |\n`
      out += `|---|---|\n`
      ;(c.series ?? []).forEach(p => { out += `| ${p.label} | ${p.value} |\n` })
      break
    }

    case 'comparison_table': {
      const t = section.data as ComparisonTable
      out += `| Metric | ${t.entities.join(' | ')} |\n`
      out += `|---|${t.entities.map(() => '---').join('|')}|\n`
      t.rows.forEach(row => {
        out += `| ${row.metric} | ${t.entities.map(e => row.values[e] ?? '—').join(' | ')} |\n`
      })
      break
    }

    case 'risk_matrix':
      ;(section.data as RiskItem[]).forEach(r => {
        out += `**[${r.severity.toUpperCase()}] ${r.title}**\n${r.description}\n\n`
      })
      break

    case 'timeline':
      ;(section.data as TimelineEvent[]).forEach(e => {
        out += `- **${e.date}** — ${e.event}\n`
      })
      break

    case 'key_quote': {
      const q = section.data as KeyQuote
      out += `> "${q.text}"\n> — *${q.source}*\n`
      break
    }

    case 'stat_card': {
      const s = section.data as { label: string; value: string; change: string }
      out += `**${s.label}**: ${s.value}  \nChange: ${s.change}\n`
      break
    }
  }

  if (section.citations?.length) {
    out += `\n*Sources: ${section.citations.map(c => `[${c}]`).join(' ')}*\n`
  }

  return out + '\n'
}

export function exportReportAsMarkdown(report: FinalReport): void {
  const lines: string[] = []

  lines.push(`# ${report.question}`)
  lines.push('')
  lines.push(`*Confidence: **${report.confidence.toUpperCase()}** · ${report.sources_count} sources analyzed*`)
  lines.push('')
  lines.push('---')
  lines.push('')
  lines.push('## Executive Summary')
  lines.push('')
  lines.push(report.executive_summary)
  lines.push('')

  if (report.stat_highlights?.length) {
    lines.push('## Key Metrics')
    lines.push('')
    lines.push('| Metric | Value | Change |')
    lines.push('|---|---|---|')
    report.stat_highlights.forEach(s => {
      lines.push(`| ${s.label} | **${s.value}** | ${s.change} |`)
    })
    lines.push('')
  }

  report.sections.forEach(s => {
    lines.push(sectionToMarkdown(s))
  })

  if (report.sources?.length) {
    lines.push('---')
    lines.push('')
    lines.push('## Sources')
    lines.push('')
    report.sources.forEach((src, i) => {
      lines.push(`${i + 1}. [${src.title}](${src.url})`)
    })
    lines.push('')
  }

  lines.push('---')
  lines.push('*Generated by FinSight — Deep Financial Research Agent*')

  const content = lines.join('\n')
  const slug = report.question
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .slice(0, 40)

  const blob = new Blob([content], { type: 'text/markdown; charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `finsight-${slug}-${Date.now()}.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
